<?php

namespace AppBundle\Repository;

/**
 * AbstractTriggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractTriggerRepository extends \Doctrine\ORM\EntityRepository
{
}
