<?php

namespace AppBundle\Repository;

/**
 * AfterCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfterCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
