<?php

namespace AppBundle\Repository;

/**
 * AfterCourseTriggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfterCourseTriggerRepository extends \Doctrine\ORM\EntityRepository
{
}
