<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Application;
use AppBundle\Entity\Promotion;
use AppBundle\Entity\State;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByPromotionAndFilters(Promotion $promotion, array $data)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')->from(Application::class, 'a')
            ->from(State::class, 'state')
            ->andWhere('s.lastName LIKE :lastName')
            ->andWhere('s.firstName LIKE :firstName')
            ->andWhere('a.currentState LIKE :currentState')
            ->andWhere('a.currentState = state.machineName')
            ->andWhere('p.id = :promotion')
            ->andWhere('state.juryCanEdit = TRUE')
            ->join('a.student', 's')
            ->join('a.promotion', 'p');

        $qb->setParameter('lastName', '%' . $data['lastName'] . '%');
        $qb->setParameter('firstName', '%' . $data['firstName'] . '%');
        $qb->setParameter('currentState', $data['currentState'] ? $data['currentState']->getMachineName() : '%%');
        $qb->setParameter('promotion', $promotion->getId());

        return $qb->getQuery()->getResult();
    }

    public function findAllWhereJuryCanEdit(Promotion $promotion){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')->from(Application::class, 'a')
            ->from(State::class, 's')
            ->join('a.promotion', 'p')
            ->andWhere('p.id = :promotion')
            ->andWhere('a.currentState = s.machineName')
            ->andWhere('s.juryCanEdit = TRUE');


        $qb->setParameter('promotion', $promotion->getId());

        return $qb->getQuery()->getResult();
    }
}
