<?php

namespace AppBundle\Repository;

/**
 * CompanyTriggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyTriggerRepository extends \Doctrine\ORM\EntityRepository
{
}
