<?php

namespace AppBundle\Repository;

/**
 * CompanyContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyContactRepository extends \Doctrine\ORM\EntityRepository
{
}
