<?php

namespace AppBundle\Repository;

/**
 * StatusModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusModificationRepository extends \Doctrine\ORM\EntityRepository
{
}
