<?php

namespace AppBundle\Repository;

/**
 * TransitionConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransitionConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
