<?php

namespace AppBundle\Repository;

/**
 * TutorTriggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorTriggerRepository extends \Doctrine\ORM\EntityRepository
{
}
