<?php

namespace AppBundle\Repository;

/**
 * WorkFlowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkFlowRepository extends \Doctrine\ORM\EntityRepository
{
}
