AppBundle\Entity\WorkFlow:
   WorkFlow_1:
        id: <randomDigitNotNull()>
        promotion: '@Promotion_1'

AppBundle\Entity\State:
   State{10..20}:
        name:  <words(2, true)>
        workflow: '@WorkFlow*'

AppBundle\Entity\Transition:
   Transition{20..50}:
        workflow: '@WorkFlow*'
        name: <words(5, true)>
        startState: '@State*'
        endState: '@State*'

AppBundle\Entity\StudentCountCondition:
   Yolo{1..5}:
        number: <numberBetween(0,25)>
        operator: '<='

AppBundle\Entity\DatetimeCondition:
   Bitch{1..5}:
        datetime: <(new \DateTime())>
        operator: '<='