<?php

namespace AppBundle\Repository\User;

/**
 * CourseManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
