<?php

namespace AppBundle\Repository\TransitionCondition;

/**
 * DatetimeConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatetimeConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
