<?php

namespace AppBundle\Repository\TransitionCondition;

/**
 * StudentCountTransitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentCountConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
